### ISSUE TITLE
Can't run Makefile.PL - Global symbol "@PATH" requires explicit package name

### ISSUE THREAD

**Issue by SentientFish** [Perl5-Alien/Alien-Libxml2#16]
Hello,

I am having trouble installing Alien-Libxml2 through cpanm.

Here is the error I am getting:
Configuring Alien-Libxml2-0.12
Running Makefile.PL
Global symbol "@PATH" requires explicit package name at /global/home/users/pierrj/perl5/lib/perl5/Alien/Build.pm line 379.
Global symbol "@PKG_CONFIG_PATH" requires explicit package name at /global/home/users/pierrj/perl5/lib/perl5/Alien/Build.pm line 382.
BEGIN not safe after errors--compilation aborted at /global/home/users/pierrj/perl5/lib/perl5/Alien/Build.pm line 1126.
Compilation failed in require at /global/home/users/pierrj/perl5/lib/perl5/Alien/Build/MM.pm line 5.
BEGIN failed--compilation aborted at /global/home/users/pierrj/perl5/lib/perl5/Alien/Build/MM.pm line 5.
Compilation failed in require at Makefile.PL line 60.
BEGIN failed--compilation aborted at Makefile.PL line 60.
-> N/A
-> FAIL Configure failed for Alien-Libxml2-0.12. See /global/home/users/pierrj/.cpanm/work/1582920803.21413/build.log for details.
-> FAIL Installing the dependencies failed: Module 'Alien::Libxml2' is not installed
-> FAIL Bailing out the installation for XML-LibXML-2.0202.
Searching XML::LibXML::Reader (0) on cpanmetadb ...
Already tried XML-LibXML-2.0202. Skipping.
-> FAIL Installing the dependencies failed: Module 'XML::LibXML' is not installed, Module 'XML::LibXML::Reader' is not installed
-> FAIL Bailing out the installation for BioPerl-1.7.7.
1 distribution installed

I know this is likely not enough information, sorry I am new to this. Please let me know if there is any more information you would need to help resolve the issue. Any and all help would be greatly appreciated. thank you.

**Comment by plicease** [comment]
Can you tell me what versions of `Alien::Build`, `Env` and `perl` you are using?

Please double check that `/global/home/users/pierrj/perl5/lib/perl5/Alien/Build.pm` matches the appropriate version on CPAN.

**Comment by SentientFish** [comment]
Thank you for your help. Here are the versions:
Alien::Build - v2.08
Env - v1.04
Perl - v5.16.3

I'm not sure what you mean about checking that `/global/home/users/pierrj/perl5/lib/perl5/Alien/Build.pm` matches the appropriate version on CPAN but I downloaded Alien::Build using cpanm so I think that means it should match.

**Comment by plicease** [comment]
I'm not able to reproduce this.  The `use Env` lines here in `Alien/Build.pm`:

https://metacpan.org/source/PLICEASE/Alien-Build-2.08/lib/Alien/Build.pm#L10-11

Should make those global package level variables, which is why I wondered if `Alien/Build.pm` or `Env.pm` had been modified.  Can verify this trivial program works:

```perl
use strict;
use warnings;
use Env qw( @PATH );
use Env qw( @PKG_CONFIG_PATH );

print "$_\n" for @PATH;
```


This is the output that I get running on Linux with those versions:

```
029b11548fa5:/work/Alien-Libxml2-0.12# perl -v

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

029b11548fa5:/work/Alien-Libxml2-0.12# which_pm Env Alien::Build
Env                  1.03       /opt/perl/5.16.3/lib/5.16.3/Env.pm
Alien::Build         2.08       /opt/perl/5.16.3/lib/site_perl/5.16.3/Alien/Build.pm
029b11548fa5:/work/Alien-Libxml2-0.12# perl Makefile.PL 
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::CommandLine
Alien::Build::CommandSequence> + xml2-config --version
Alien::Build::CommandSequence> [output consumed by Alien::Build recipe]
Alien::Build::CommandSequence> + xml2-config --cflags
Alien::Build::CommandSequence> [output consumed by Alien::Build recipe]
Alien::Build::CommandSequence> + xml2-config --libs
Alien::Build::CommandSequence> [output consumed by Alien::Build recipe]
Alien::Libxml2 is designed to work with XML::LibXML.

The installed system version of libxml2 2.9.4 is not compatible with XML::LibXML (and probably buggy)!

  - don't expect XML::LibXML to build or work correctly with this version of libxml2!
  - don't report errors with this version of libxml2!
  - don't send patches for this version of libxml2!

XML::LibXML typically attempts to install with this version anyway, so will we.
Checking if your kit is complete...
Looks good
Warning: prerequisite Test2::V0 0.000060 not found.
Generating a Unix-style Makefile
Writing Makefile for Alien::Libxml2
Writing MYMETA.yml and MYMETA.json
```

**Comment by SentientFish** [comment]
It's working now, I'm not exactly sure why... I think reinstalling Env and Alien::Build is what solved the issue, I think you were right that those files must have gotten modified somehow

Very sorry for wasting your time, looks like I gave up 10 minutes too early. Thank you very much for the help.

**Comment by plicease** [comment]
> It's working now, I'm not exactly sure why... I think reinstalling Env and Alien::Build is what solved the issue, I think you were right that those files must have gotten modified somehow

Great!

> Very sorry for wasting your time, looks like I gave up 10 minutes too early. Thank you very much for the help.

No problem.  It's not always obvious if there is a glitch or something wrong with the environment or an actual bug.
