### ISSUE TITLE
"SEE ALSO" documentation incorrect

### ISSUE THREAD

**Issue by tobyink** [Perl5-Alien/Alien-Libxml2#18]
Documentation says:

> There was an already existing Alien::LibXML, but it uses the older Alien::Build::ModuleBuild and has not been actively maintained for a while.

And:

> Alien::LibXML
> Unmaintained Alien for the same library.

Alien::LibXML is still actively maintained. There's only one open bug and it only affects a platform that I don't have access to test on.

It's not being actively *developed* because I consider it to be feature-complete.

**Comment by plicease** [comment]
Sorry!  I will update the documentation.

In defense my when I wrote that critical PR https://github.com/tobyink/p5-alien-libxml/pull/5 had remained unanswered for over a year and would remain as such for another year.

**Comment by plicease** [comment]
Fixed in 0.15

**Comment by tobyink** [comment]
Yeah, sorry that took a while. When you read something on Github it disappears off your notifications and it can kind of get forgotten about easily. RT generally fits better with my way of working on stuff.
