### ISSUE TITLE
Unable to build Alien-Libxml2 on AIX 7.1

### ISSUE THREAD

**Issue by hpslmcg** [Perl5-Alien/Alien-Libxml2#8]
```
100 $ XMLPREFIX=/proj/edi/opt/libxml2/2.9.9 perl Makefile.PL PREFIX=/proj/edi/opt/perl/perl5.24.4_64 LIB=/proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Alien::Build::CommandSequence> + xml2-config --version
Alien::Build::CommandSequence> [output consumed by Alien::Build recipe]
Alien::Build::CommandSequence> + xml2-config --cflags
Alien::Build::CommandSequence> [output consumed by Alien::Build recipe]
Alien::Build::CommandSequence> + xml2-config --libs
Alien::Build::CommandSequence> [output consumed by Alien::Build recipe]
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Alien::Libxml2
Writing MYMETA.yml and MYMETA.json


101 $ make
cp lib/Alien/Libxml2.pm blib/lib/Alien/Libxml2.pm
        "/proj/edi/opt/perl/perl5.24.4_64/bin/perl" -MAlien::Build::MM=cmd -e prefix site /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
main> prefix /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all/auto/share/dist/Alien-Libxml2
        "/proj/edi/opt/perl/perl5.24.4_64/bin/perl" -MAlien::Build::MM=cmd -e version 0.07
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
        "/proj/edi/opt/perl/perl5.24.4_64/bin/perl" -MAlien::Build::MM=cmd -e download
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
        "/proj/edi/opt/perl/perl5.24.4_64/bin/perl" -MAlien::Build::MM=cmd -e build
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Use of uninitialized value in subroutine entry at /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/PkgConfig.pm line 873.
Use of uninitialized value $search_paths[0] in join or string at /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/PkgConfig.pm line 878.
Alien::Build::Plugin::PkgConfig::PP> Trying to load the pkg-config information from the source code build
Alien::Build::Plugin::PkgConfig::PP> of your package failed
Alien::Build::Plugin::PkgConfig::PP> You are currently using the pure-perl implementation of pkg-config
Alien::Build::Plugin::PkgConfig::PP> (AB Plugin is named PkgConfig::PP, which uses PkgConfig.pm
Alien::Build::Plugin::PkgConfig::PP> It may work better with the real pkg-config.
Alien::Build::Plugin::PkgConfig::PP> Try installing your OS' version of pkg-config or unset ALIEN_BUILD_PKG_CONFIG
Alien::Build::Plugin::Core::Legacy> adding legacy hash to config
Alien::Build::Plugin::Core::Gather> mkdir -p /home/hpslmcg/.cpan/build/Alien-Libxml2-0.07-0/blib/lib/auto/share/dist/Alien-Libxml2/_alien
Manifying 1 pod document


102 $ make test
        PERL_DL_NONLAZY=1 "/proj/edi/opt/perl/perl5.24.4_64/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00_diag.t ........ 1/? #
#
#
# HARNESS_ACTIVE=1
# HARNESS_VERSION=3.36_01
# LANG=en_US
# LC__FASTMSG=true
# PERL5LIB=/home/hpslmcg/.cpan/build/Alien-Libxml2-0.07-0/blib/lib:/home/hpslmcg/.cpan/build/Alien-Libxml2-0.07-0/blib/arch
# PERL_DL_NONLAZY=1
# PERL_HOME=/proj/edi/opt/perl/perl5.24.4_64/
# PERL_VERSION=5.24.4_64
# SHELL=/bin/sh
#
#
#
# PERL5LIB path
# /home/hpslmcg/.cpan/build/Alien-Libxml2-0.07-0/blib/lib
# /home/hpslmcg/.cpan/build/Alien-Libxml2-0.07-0/blib/arch
#
#
#
# perl                                     5.024004
# Alien::Base                              1.69
# Alien::Build                             1.69
# Alien::Build::MM                         1.69
# Alien::Build::Plugin::Build::SearchDep   1.69
# Alien::Build::Plugin::Prefer::BadVersion 1.69
# ExtUtils::CBuilder                       0.280225
# ExtUtils::MakeMaker                      7.1002
# Test2::V0                                0.000121
# Test::Alien                              1.69
#
#
#
# version        =
# cflags         =
# cflags_static  =
# libs           =
# libs_static    =
#
#
#
t/00_diag.t ........ ok
t/alien_libxml2.t .. 1/?
# Failed test 'xs'
# at t/alien_libxml2.t line 10.
#   ExtUtils::CBuilder->compile failed
#     error building testalienZ2twy/test.o from 'testalienZ2twy/test.c' at /proj/edi/opt/perl/perl5.24.4_64/lib/5.24.4/ExtUtils/CBuilder/Base.pm line 174.
#     cc_r -q64 -I/proj/edi/opt/perl/perl5.24.4_64/lib/5.24.4/aix-thread-multi-64all/CORE -c -D_ALL_SOURCE -D_ANSI_C_SOURCE -D_POSIX_SOURCE -qmaxmem=-1 -qnoansialias -qlanglvl=extc99 -DUSE_NATIVE_DLOPEN -DNEED_PTHREAD_INIT -I/usr/local/include -q64 -DUSE_64_BIT_ALL -q64 -O -o testalienZ2twy/test.o testalienZ2twy/test.c
#     "testalienZ2twy/test.xs", line 5.10: 1506-296 (S) #include file <libxml/parser.h> not found.
#     "testalienZ2twy/test.xs", line 6.10: 1506-296 (S) #include file <libxml/tree.h> not found.
#     "testalienZ2twy/test.xs", line 13.5: 1506-045 (S) Undeclared identifier xmlDoc.
#     "testalienZ2twy/test.xs", line 13.13: 1506-045 (S) Undeclared identifier doc.
#     "testalienZ2twy/test.xs", line 13.17: 1506-277 (S) Syntax error: possible missing ';' or ','?
#     "testalienZ2twy/test.xs", line 14.5: 1506-045 (S) Undeclared identifier xmlNode.
#     "testalienZ2twy/test.xs", line 14.14: 1506-045 (S) Undeclared identifier root_element.
t/alien_libxml2.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests

Test Summary Report
-------------------
t/alien_libxml2.t (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=2, Tests=4,  1 wallclock secs ( 0.03 usr  0.01 sys +  0.71 cusr  0.13 csys =  0.88 CPU)
Result: FAIL
Failed 1/2 test programs. 1/4 subtests failed.
make: 1254-004 The error code from the last command is 1.


Stop.
```

**Comment by plicease** [comment]
Can you try version `0.08_01`?

**Comment by plicease** [comment]
Can be found here:
https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Alien-Libxml2-0.08_01.tar.gz

**Comment by hpslmcg** [comment]
It worked. The output is below.

52 $ XMLPREFIX=/proj/edi/opt/libxml2/2.9.9 perl Makefile.PL PREFIX=/proj/edi/opt/perl/perl5.24.4_64 LIB=/proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4                                                                                                                   Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Alien::Build::CommandSequence> + xml2-config --version
Alien::Build::CommandSequence> [output consumed by Alien::Build recipe]
Alien::Build::CommandSequence> + xml2-config --cflags
Alien::Build::CommandSequence> [output consumed by Alien::Build recipe]
Alien::Build::CommandSequence> + xml2-config --libs
Alien::Build::CommandSequence> [output consumed by Alien::Build recipe]
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Alien::Libxml2
Writing MYMETA.yml and MYMETA.json


53 $ make
cp lib/Alien/Libxml2.pm blib/lib/Alien/Libxml2.pm
        "/proj/edi/opt/perl/perl5.24.4_64/bin/perl" -MAlien::Build::MM=cmd -e prefix site /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
main> prefix /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all/auto/share/dist/Alien-Libxml2
        "/proj/edi/opt/perl/perl5.24.4_64/bin/perl" -MAlien::Build::MM=cmd -e version 0.08_01
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
        "/proj/edi/opt/perl/perl5.24.4_64/bin/perl" -MAlien::Build::MM=cmd -e download
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
        "/proj/edi/opt/perl/perl5.24.4_64/bin/perl" -MAlien::Build::MM=cmd -e build
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Use of uninitialized value in subroutine entry at /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/PkgConfig.pm line 873.
Use of uninitialized value $search_paths[0] in join or string at /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/PkgConfig.pm line 878.
Alien::Build::Plugin::PkgConfig::PP> Trying to load the pkg-config information from the source code build
Alien::Build::Plugin::PkgConfig::PP> of your package failed
Alien::Build::Plugin::PkgConfig::PP> You are currently using the pure-perl implementation of pkg-config
Alien::Build::Plugin::PkgConfig::PP> (AB Plugin is named PkgConfig::PP, which uses PkgConfig.pm
Alien::Build::Plugin::PkgConfig::PP> It may work better with the real pkg-config.
Alien::Build::Plugin::PkgConfig::PP> Try installing your OS' version of pkg-config or unset ALIEN_BUILD_PKG_CONFIG
Alien::Build::Plugin::Core::Legacy> adding legacy hash to config
Alien::Build::Plugin::Core::Gather> mkdir -p /tmp/Alien-Libxml2-0.08_01/blib/lib/auto/share/dist/Alien-Libxml2/_alien
Manifying 1 pod document


54 $ make test
        PERL_DL_NONLAZY=1 "/proj/edi/opt/perl/perl5.24.4_64/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00_diag.t ........ 1/? #
#
#
# HARNESS_ACTIVE=1
# HARNESS_VERSION=3.36_01
# LANG=en_US
# LC__FASTMSG=true
# PERL5LIB=/tmp/Alien-Libxml2-0.08_01/blib/lib:/tmp/Alien-Libxml2-0.08_01/blib/arch
# PERL_DL_NONLAZY=1
# PERL_HOME=/proj/edi/opt/perl/perl5.24.4_64/
# PERL_VERSION=5.24.4_64
# SHELL=/bin/sh
#
#
#
# PERL5LIB path
# /tmp/Alien-Libxml2-0.08_01/blib/lib
# /tmp/Alien-Libxml2-0.08_01/blib/arch
#
#
#
# perl                                     5.024004
# Alien::Base                              1.69
# Alien::Build                             1.69
# Alien::Build::MM                         1.69
# Alien::Build::Plugin::Build::SearchDep   1.69
# Alien::Build::Plugin::Prefer::BadVersion 1.69
# ExtUtils::CBuilder                       0.280225
# ExtUtils::MakeMaker                      7.1002
# Test2::V0                                0.000121
# Test::Alien                              1.69
#
#
#
# version        = 2.7.8
# cflags         = -I/proj/edi/opt/libxml2/2.7.8_64/include/libxml2
# cflags_static  = -I/proj/edi/opt/libxml2/2.7.8_64/include/libxml2
# libs           = -L/proj/edi/opt/libxml2/2.7.8_64/lib -lxml2 -lpthread -liconv -lm
# libs_static    = -L/proj/edi/opt/libxml2/2.7.8_64/lib -lxml2 -lpthread -liconv -lm
#
#
#
t/00_diag.t ........ ok
t/alien_libxml2.t .. ok
All tests successful.
Files=2, Tests=4,  3 wallclock secs ( 0.03 usr  0.01 sys +  0.82 cusr  0.16 csys =  1.02 CPU)
Result: PASS
        "/proj/edi/opt/perl/perl5.24.4_64/bin/perl" -MAlien::Build::MM=cmd -e test
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Target "test" is up to date.


55 $ make install
Manifying 1 pod document
Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
Installing /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all/auto/Alien/Libxml2/Libxml2.txt
Installing /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all/Alien/Libxml2.pm
Installing /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all/Alien/Libxml2/Install/Files.pm
Installing /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all/auto/share/dist/Alien-Libxml2/_alien/alien.json
Installing /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all/auto/share/dist/Alien-Libxml2/_alien/alienfile
Installing /proj/edi/opt/perl/perl5.24.4_64/man/man3/Alien::Libxml2.3
Appending installation info to /proj/edi/opt/perl/perl5.24.4_64/lib/site_perl/5.24.4/aix-thread-multi-64all/perllocal.pod

**Comment by plicease** [comment]
Great.  The latest production version `0.09` should also work.

**Comment by hpslmcg** [comment]
I successfully installed it using cpan.
